development:
  adapter: postgresql
  encoding: unicode
  database: db/store_development
  pool: 5
  username: store_admin
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: db/store_test
  pool: 5
  username: store_admin
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: db/store_production
  pool: 5
  username: store_admin
  password: password1
